#!/bin/sh

export LANG=ja_JP.eucJP

if [ -f $HOME/.Xresources ]; then
	xrdb -load $HOME/.Xresources
fi

OS=`uname -s`
case $OS in
FreeBSD)
  # start some nice programs
  export XMODIFIERS="@im=SCIM"
  export GTK_IM_MODULE=xim
  echo '*inputMethod: SCIM' | xrdb -merge
  scim -d &

  # eval `ssh-agent -s`
  # ssh-add </dev/null

  # kterm -geometry 80x30+0+0 &
  # xclock -geometry 100x100-1+1 &

  sawfish
  # fluxbox
  # twm
  # startkde

  # eval `ssh-agent -k -s`
  ;;
Darwin)
  quartz-wm
  ;;
esac
